### ISSUE TITLE
NF10: Anbieter kontaktieren

### ISSUE THREAD

**Issue by Der-Alex** [oforge/oforge-core#14]
### Beschreibung: 
Jeder Nutzer der Webseite kann Anbietern eines Inserats eine Nachricht über das Portal schreiben sowie die Anbieter-Kontaktdaten einsehen.

### Modul:
Messages

### Tasks:

- [ ] #73 Erstelle einen Message Controller
- [ ] #74 Erstelle einen MessageService
- [ ] #76 Erstelle ein Frontend Template für den Message Controller
