### ISSUE TITLE
NF2: Ein Portalnutzer kann sich am Portal an- und abmelden

### ISSUE THREAD

**Issue by mys3lf** [oforge/oforge-core#2]
### Beschreibung: 
Ein Nutzer kann sich mit seinen Benutzerdaten am Portal an- oder abmelden.

### Modul:
Auth

### Tasks:
- [x]  #70 Erstelle einen LoginController
- [x]  #71 Erstelle einen LoginService
- [x]  #72 Erstelle ein Login Template

### Abhängigkeiten
- [ ] #6 Passwort vergessen
