### ISSUE TITLE
NF33: Nutzer anlegen, bearbeiten, löschen

### ISSUE THREAD

**Issue by Der-Alex** [oforge/oforge-core#35]
### Beschreibung: 
Ein Administrator kann Nutzer anlegen, bearbeiten und löschen.
Ein Administrator kann Admin Backend Nutzer verwalten.
### Modul: 
UserManagement

### Tasks: 
- [ ] #79 Erstelle einen UserController im Admin Backend
- [ ] #80 Erstelle ein Backend User Template
- [ ] #82 Erstelle ein Backend Template für die Pflege von Systemnutzern (Admin, Moderator)

### Abhängigkeiten:
- [ ] #4 Ein Nutzer kann sich am Portal registrieren
- [ ] #39 Nutzerrolle zuweisen
