### ISSUE TITLE
NF1: Ein Nutzer kann sich am Portal registrieren

### ISSUE THREAD

**Issue by Der-Alex** [oforge/oforge-core#4]
### Beschreibung:
Ein Nutzer kann sich am Portal registrieren, um sich ein Nutzerprofil anzulegen.

### Modul:
Auth

### Tasks:
- [ ] #66 Erstelle einen AuthService
- [ ] #67 Erstelle einen RegistrationService
- [ ] #68 Erstelle einen RegistrationController
- [ ] #69 Erstelle ein Registration Template

### Abhängigkeiten
- [ ] #6 Passwort vergessen
