### ISSUE TITLE
NF5: Nutzerprofil pflegen

### ISSUE THREAD

**Issue by Der-Alex** [oforge/oforge-core#7]
### Beschreibung:
Als Portal Nutzer kann ich mein persönliches Profil bearbeiten oder auch mein Passwort ändern. Der Umfang der speicherbaren Daten hängt dabei von den bestellten Premium-Funktionen ab.
Als Moderator / Admin kann ich die Daten der registrierten Benutzer ändern. 

### Modul: 
UserManagement

### Tasks: 
- [ ] #77 Erstelle einen UserService
- [ ] #78 Erstelle einen UserController für das Portal

### Abhängigkeiten
- [ ] #5 Der Nutzer kann sein Profil löschen
