### ISSUE TITLE
NF40 Ein Systemnutzer kann sich am Admin Backend anmelden

### ISSUE THREAD

**Issue by Der-Alex** [oforge/oforge-core#89]
### Beschreibung: 
Ein Systemnutzer kann sich mit seinen Benutzerdaten am Admin Backend an- oder abmelden.

### Modul:
Auth

### Tasks:
- [ ]  #66 Erstelle einen AuthService
- [ ]  #87 Erstelle einen BackendLoginService
- [ ]  #88 Erstelle einen BackendLoginController

**Comment by mys3lf** [comment]
Scheint fertig. Bitte kontrollieren und schließen

**Comment by Der-Alex** [comment]
fertig
